### ISSUE TITLE
Project Checkpoint 1 - Instructor Notes

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [pltollefson/Game-Completion-Archive#1]
Hi Parker, I realize I'm peeking into your repo before the checkpoint is actually due tonight, but I wanted to jot a few things down so that I don't forget to ask about them. 

Your user stories look good. I think you have a solid MVP here.

- [x] What will a user who is not registered/logged in be able to do? Is there a landing page or anything for them to see, or does a user have to log in to access anything?
- [x] Be sure to update your problem statement in the readme.md. This will serve as the homepage of your application and will be the first thing prospective employers see, so be sure to include a nice, professional explanation of your project including technologies that you'll be using.
- [x] Time log likely needs some updating - this should include all work for this class (unless you are keeping a weekly work log elsewhere - if so, just let me know where to find it).
- [x] Project plan?
- [x] Screens/wireframes?
- [x] Have you thought about which web service or api you will use yet?

**Comment by pltollefson** [comment]
Still need to work on the project plan, and look into the IGDB, as well as other, APIs.
